### ISSUE TITLE
can we have ACL and templating system?

### ISSUE THREAD

**Issue by ibnoe** [JasonBaier/ci3-fire-starter#40]
i already use this for several project..  but this project lack of templating system and ACL
i add thi to my_controller

  function set_template($template_file="template.php")
    {
        // make sure that $template_file has .php extension
        $template_file = substr($template_file, -4) == '.php' ? $template_file : ($template_file . ".php");

        $this->template = "../../{$this->settings->themes_folder}/{$this->settings->theme}/{$template_file}";
    }
    public function view($view='',$param=NULL)
    {
        $data = $this->includes;
        $data['content'] = $this->load->view($view, $param, TRUE);
        $this->load->view($this->template, $data);

    }

**Comment by JasonBaier** [comment]
I opted not to include an ACL because not everyone might want or need something that specific. There are also so many variations of ACLs... which one should be used? Some might even want something more advanced like RBAC. It makes more sense to keep the simple login system that is currently in place and leave it up to the developer to add their own preferences.

For that same reason, I did not include a templating system. Everyone has their own preferences, and I didn't want to add something with yet another learning curve. The goal of this application was to keep it small and simple.

You could always fork this project and add your preferred libraries for your future projects.
